#-------------------------------------------------------------------------------------
#                                                            
#   ,---.   ,--.                        ,--.     ,--.        
#  '   .-',-'  '-. ,--,--.,--.--. ,---. |  ,---. `--' ,---.  
#  `.  `-.'-.  .-'' ,-.  ||  .--'(  .-' |  .-.  |,--.| .-. | 
#  .-'    | |  |  \ '-'  ||  |   .-'  `)|  | |  ||  || '-' ' 
#  `-----'  `--'   `--`--'`--'   `----' `--' `--'`--'|  |-'  
#                                                    `--'    
#
#      , _ ,        RESUME:  Custom pront for terminals and complement
#     ( o o )                because i use OhMyZsh.
#    /'` ' `'\
#    |'''''''|      AUTHOR:  Andr3xDev
#    |\\'''//|      URL: (https://github.com/Andr3xDev/Dotfiles)
#       """                                              
#-------------------------------------------------------------------------------------


#------------------------------------------------------------
#   Format
#------------------------------------------------------------

format = """
[â”Œâ”€â”€](bold green)$os\
$directory\
$git_branch\
$git_status \
$aws\
$memory_usage\
$docker_context\
$cmd_duration\
$status
[â””â”€â¤](bold green) """

#--- properties ---#
add_newline = true 
continuation_prompt = "â–¶â–¶ "



#------------------------------------------------------------
#   Palette
#------------------------------------------------------------

palette = 'gruvbox_material'

[palettes.gruvbox_material]
background = "#282828"
green = '#a9b665'
red = '#ea6962'
blue = '#7daea3'
yellow = '#d8a657'
orange = '#e78a4e'



#------------------------------------------------------------
#   Elements
#------------------------------------------------------------

[os]
format = '[â”ƒ](fg:green bg:background)[ ïŒƒ  ](fg:white bg:background) '
disabled = false

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 3
home_symbol = ' ó°‹œ ~'
read_only = ' ï€£ '
format = '[â”ƒ](fg:blue bg:background)[$path ](fg:white bg:background)[$read_only ](fg:white bg:background)'

[git_branch]
format = ' [â”ƒ](fg:yellow bg:background)[ ï˜ $branch ](fg:white bg:background)'
truncation_symbol = 'â€¦/'

[git_status]
format = '[$all_status$ahead_behind ](fg:white bg:background)'
conflicted = 'ğŸ³'
up_to_date = ''
untracked = 'ï”© '
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ï£– '
modified = 'ï„ '
staged = '[++\($count\)](fg:white bg:background)'
renamed = 'ïª¶ '
deleted = 'ï€” '

[cmd_duration]
min_time = 250
format = "[â”ƒ](fg:orange bg:background)[ â± $duration ](fg:white bg:background)"
show_milliseconds = true
disabled = false

[status]
disabled = false
format = '[â”ƒ](fg:orange bg:background)[ âœ˜ ](fg:red bg:background)'



#------------------------------------------------------------
#   Extra Elements
#------------------------------------------------------------

[line_break]
disabled = true

[aws]
symbol = "îŒ½  "

[docker_context]
symbol = "ïŒˆ "
