#-------------------------------------------------------------------------------------
#                                                            
#       ,---.   ,--.                        ,--.     ,--.        
#     "   .-",-"  "-. ,--,--.,--.--. ,---. |  ,---. `--" ,---.  
#     `.  `-."-.  .-"" ,-.  ||  .--"(  .-" |  .-.  |,--.| .-. | 
#     .-"    | |  |  \ "-"  ||  |   .-"  `)|  | |  ||  || "-" " 
#     `-----"  `--"   `--`--"`--"   `----" `--" `--"`--"|  |-"  
#                                                       `--"    
#             _______
#　　　　　 /  ＞　　フ     
#　　　　　| 　_　 _ l      RESUME: Custom pront for terminals and complement
#　 　　　／` ミ＿xノ               because i use OhMyZsh.
#　　 　 /　　　 　 |
#　　　 /　 ヽ　　 ﾉ
#　 　 │　　|　|　|         AUTHOR:  Andr3xDev
#　／￣|　　 |　|　|        URL: https://github.com/Andr3xDev/HyprPharch
#　| (￣ヽ＿_ヽ_)__)
#　＼二つ
#-------------------------------------------------------------------------------------


#-------------------------------------------------------------------------------------
#   Format
#-------------------------------------------------------------------------------------

format = """
$line_break \
$os \
$directory\
$git_branch\
$git_status\
$cmd_duration\
$docker\
$aws\
$status
[ └─➤ ](blue)"""

#--- properties ---#
add_newline = true 
continuation_prompt = "▶▶ "


#-------------------------------------------------------------------------------------
#   Palette
#-------------------------------------------------------------------------------------

palette = "gruvbox_material"

[palettes.gruvbox_material]
background = ""
overlay = "#32302f"
text = "#d4be98"
green = "#a9b665"
red = "#ea6962"
blue = "#7daea3"
yellow = "#d8a657"
orange = "#e78a4e"


#-------------------------------------------------------------------------------------
#   Elements
#-------------------------------------------------------------------------------------

[os]
format = "[](bold fg:blue)[](bold fg:overlay bg:blue)[   ](bold fg:blue bg:overlay)[◤](bold fg:overlay)"
disabled = false

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 3
truncate_to_repo = true
home_symbol = " ~"
read_only = "  "
format = "[](bold fg:green)[](bold fg:overlay bg:green)[  ](bold fg:text bg:overlay)[$path](bold fg:text bg:overlay)[$read_only ](bold fg:orange bg:overlay)[◤](bold fg:overlay)"

[git_branch]
format = "[](bold fg:green)[](bold fg:overlay bg:green)[  ](bold fg:text bg:overlay)[$branch](bold fg:text bg:overlay)"
truncation_symbol = "…/"

[git_status]
format = "[ $all_status$ahead_behind ](bold fg:orange bg:overlay)[◤](bold fg:overlay)"
stashed = " "
ahead = " ↑"
behind = " ↓"
diverged = " ↕"
conflicted = " "
untracked = " ?"
staged = " +"
modified = " !"
renamed = " »"
deleted = " ✘"

[cmd_duration]
min_time = 0
format = "[](bold fg:green)[](bold fg:overlay bg:green)[ ⏱  ](bold fg:text bg:overlay)[$duration ](bold fg:text bg:overlay)[◤](bold fg:overlay)"
show_milliseconds = true

[status]
disabled = false
format = "[](bold fg:red)[](bold fg:overlay bg:red)[ ✘ ](bold fg:red bg:overlay)[◤](bold fg:overlay)"


#-------------------------------------------------------------------------------------
#   Extra Elements
#-------------------------------------------------------------------------------------

[line_break]
disabled = false

[aws]
symbol = " "
format = "[◢](bold fg:overlay)[ $symbol](bold fg:pine bg:overlay)[◤](bold fg:overlay)"

[docker_context]
symbol = " "
format = "[◢](bold fg:overlay)[ $symbol](bold fg:pine bg:overlay)[◤](bold fg:overlay)"
